In [71]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import os
warnings.filterwarnings("ignore")

sns.set_theme(style="whitegrid")
print('Libraries loaded ✓')

Libraries loaded ✓

In [54]:
#load dataset
df_raw = pd.read_csv("../data/raw_data/bank-additional-full.csv",
                    sep=";"
                    )

df_raw.head(1)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

Inspect the data set

In [55]:
df_raw.shape

(41188, 21)

In [56]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [57]:
df_raw.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

Data Quality Check

In [58]:
df_raw.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [59]:
df_raw.duplicated().sum()

12

In [60]:
duplicate_counts = (df_raw.value_counts().reset_index(name="Count"))

duplicate_counts[duplicate_counts["Count"] > 1]

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,Count
0,36,retired,married,unknown,no,no,no,telephone,jul,thu,...,999,0,nonexistent,1.4,93.918,-42.7,4.966,5228.1,no,2
1,39,blue-collar,married,basic.6y,no,no,no,telephone,may,thu,...,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no,2
2,27,technician,single,professional.course,no,no,no,cellular,jul,mon,...,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no,2
3,55,services,married,high.school,unknown,no,no,cellular,aug,mon,...,999,0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,no,2
4,41,technician,married,professional.course,no,yes,no,cellular,aug,tue,...,999,0,nonexistent,1.4,93.444,-36.1,4.966,5228.1,no,2
5,47,technician,divorced,high.school,no,yes,no,cellular,jul,thu,...,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no,2
6,35,admin.,married,university.degree,no,yes,no,cellular,may,fri,...,999,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1,no,2
7,45,admin.,married,university.degree,no,no,no,cellular,jul,thu,...,999,0,nonexistent,-2.9,92.469,-33.6,1.072,5076.2,yes,2
8,32,technician,single,professional.course,no,yes,no,cellular,jul,thu,...,999,0,nonexistent,1.4,93.918,-42.7,4.968,5228.1,no,2
9,71,retired,single,university.degree,no,no,no,telephone,oct,tue,...,999,0,nonexistent,-3.4,92.431,-26.9,0.742,5017.5,no,2
10,39,admin.,married,university.degree,no,no,no,cellular,nov,tue,...,999,0,nonexistent,-0.1,93.200,-42.0,4.153,5195.8,no,2
11,24,services,single,high.school,no,yes,no,cellular,apr,tue,...,999,0,nonexistent,-1.8,93.075,-47.1,1.423,5099.1,no,2

In [61]:
cat_cols = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'poutcome' ]
for col in cat_cols:
    print(f'{col} ({df_raw[col].nunique()} unique): {sorted(df_raw[col].dropna().unique())}')
    print()

job (12 unique): ['admin.', 'blue-collar', 'entrepreneur', 'housemaid', 'management', 'retired', 'self-employed', 'services', 'student', 'technician', 'unemployed', 'unknown']

marital (4 unique): ['divorced', 'married', 'single', 'unknown']

education (8 unique): ['basic.4y', 'basic.6y', 'basic.9y', 'high.school', 'illiterate', 'professional.course', 'university.degree', 'unknown']

default (3 unique): ['no', 'unknown', 'yes']

housing (3 unique): ['no', 'unknown', 'yes']

loan (3 unique): ['no', 'unknown', 'yes']

contact (2 unique): ['cellular', 'telephone']

month (10 unique): ['apr', 'aug', 'dec', 'jul', 'jun', 'mar', 'may', 'nov', 'oct', 'sep']

day_of_week (5 unique): ['fri', 'mon', 'thu', 'tue', 'wed']

poutcome (3 unique): ['failure', 'nonexistent', 'success']

In [62]:
unknown_summary = {}

for col in df_raw.select_dtypes(include="object").columns:
    n_unknown = (df_raw[col] == 'unknown').sum()
    if n_unknown > 0:
        unknown_summary[col] = n_unknown
        print(f"{col}: {n_unknown} unknown ({n_unknown/len(df_raw):.1%})")

job: 330 unknown (0.8%)
marital: 80 unknown (0.2%)
education: 1731 unknown (4.2%)
default: 8597 unknown (20.9%)
housing: 990 unknown (2.4%)
loan: 990 unknown (2.4%)

In [63]:
cols_to_check = ['job', 'marital', 'education', 'default', 'housing', 'loan']

for col in cols_to_check:
    print(f"\n{'='*45}")
    print(f"  Column: {col.upper()}")
    print(f"{'='*45}")
    
    counts    = df_raw[col].value_counts()
    percents  = df_raw[col].value_counts(normalize=True) * 100
    
    summary = pd.DataFrame({
        'Category'   : counts.index,
        'Count'      : counts.values,
        'Percentage' : percents.values.round(2)
    })
    summary['Percentage'] = summary['Percentage'].apply(lambda x: f"{x}%")
    
    print(summary.to_string(index=False))

=============================================
  Column: JOB
=============================================
     Category  Count Percentage
       admin.  10422      25.3%
  blue-collar   9254     22.47%
   technician   6743     16.37%
     services   3969      9.64%
   management   2924       7.1%
      retired   1720      4.18%
 entrepreneur   1456      3.54%
self-employed   1421      3.45%
    housemaid   1060      2.57%
   unemployed   1014      2.46%
      student    875      2.12%
      unknown    330       0.8%

=============================================
  Column: MARITAL
=============================================
Category  Count Percentage
 married  24928     60.52%
  single  11568     28.09%
divorced   4612      11.2%
 unknown     80      0.19%

=============================================
  Column: EDUCATION
=============================================
           Category  Count Percentage
  university.degree  12168     29.54%
        high.school   9515      23.1%
           basic.9y   6045     14.68%
professional.course   5243     12.73%
           basic.4y   4176     10.14%
           basic.6y   2292      5.56%
            unknown   1731       4.2%
         illiterate     18      0.04%

=============================================
  Column: DEFAULT
=============================================
Category  Count Percentage
      no  32588     79.12%
 unknown   8597     20.87%
     yes      3      0.01%

=============================================
  Column: HOUSING
=============================================
Category  Count Percentage
     yes  21576     52.38%
      no  18622     45.21%
 unknown    990       2.4%

=============================================
  Column: LOAN
=============================================
Category  Count Percentage
      no  33950     82.43%
     yes   6248     15.17%
 unknown    990       2.4%

Treatments for Data Quality Issues

In [64]:
#dropping duplicates
df_raw= df_raw.drop_duplicates().reset_index(drop=True)

df_raw.shape

(41176, 21)

In [65]:
# Mode imputation for job, marital, housing, loan columns as unknown percentage is comparatively less
for col in ['job', 'marital', 'housing', 'loan']:
    mode_val = df_raw[col][df_raw[col] != 'unknown'].mode()[0]
    unknown_count = (df_raw[col] == 'unknown').sum()
    
    df_raw[col] = df_raw[col].replace('unknown', mode_val)
    
    print(f"Column : {col}")
    print(f"Mode   : '{mode_val}'")
    print(f"Rows imputed : {unknown_count}")
    print(f"Remaining 'unknown' : {(df_raw[col] == 'unknown').sum()}")
    print("-" * 35)

Column : job
Mode   : 'admin.'
Rows imputed : 330
Remaining 'unknown' : 0
-----------------------------------
Column : marital
Mode   : 'married'
Rows imputed : 80
Remaining 'unknown' : 0
-----------------------------------
Column : housing
Mode   : 'yes'
Rows imputed : 990
Remaining 'unknown' : 0
-----------------------------------
Column : loan
Mode   : 'no'
Rows imputed : 990
Remaining 'unknown' : 0
-----------------------------------

In [68]:
# Group-by mode imputation for Education based on Job
mode_education_per_job = df_raw[df_raw['education'] != 'unknown'].groupby('job')['education'].agg(lambda x: x.mode()[0])

def impute_education(row):
    if row['education'] == 'unknown' and row['job'] in mode_education_per_job:
        return mode_education_per_job[row['job']]
    return row['education']

df_raw['education'] = df_raw.apply(impute_education, axis=1)

In [74]:
print(os.getcwd())

D:\DataScience MSc\Module_Machine Learning\course Work\Bank_Marketing_Prediction\Project_MachineLearning\notebooks

In [75]:
os.chdir(r"D:\DataScience MSc\Module_Machine Learning\course Work\Bank_Marketing_Prediction\Project_MachineLearning")

In [76]:
print(os.getcwd())

D:\DataScience MSc\Module_Machine Learning\course Work\Bank_Marketing_Prediction\Project_MachineLearning

In [77]:
df_raw.to_csv("data/processed_data/bank-additional-full-processed.csv", index=False)

# Verify it saved correctly
saved_df = pd.read_csv("data/processed_data/bank-additional-full-processed.csv")

print("File saved successfully!")
print(f"   Location : data/processed_data/bank-additional-full-processed.csv")
print(f"   Rows     : {saved_df.shape[0]}")
print(f"   Columns  : {saved_df.shape[1]}")

File saved successfully!
   Location : data/processed_data/bank-additional-full-processed.csv
   Rows     : 41176
   Columns  : 21